"""Bank SMS templates and locale lists for generate_synth.py."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Locale:
    firsts: tuple[str, ...]
    surnames: tuple[str, ...]
    shops: tuple[str, ...]
    brands: tuple[str, ...]


@dataclass(frozen=True)
class Template:
    key: str
    bank: str
    country: str
    currency: str
    sender_core: str
    txn_type: str
    body: str
    required: tuple[str, ...]
    expense_type: str = "unknown"
    one_word_merchant: bool = False
    merchant_upper: bool = False


LOCALES: dict[str, Locale] = {
    "India": Locale(
        ("Ravi", "Priya", "Ankit", "Neha", "Rahul", "Pooja", "Arjun", "Meera"),
        ("Sharma", "Patel", "Verma", "Gupta", "Singh", "Kumar", "Reddy", "Iyer"),
        ("Kirana Store", "Medical Store", "Sweets Corner", "Tea Stall", "Mobile Shop"),
        ("Amazon Pay", "Swiggy", "Zomato", "IRCTC", "PhonePe", "Blinkit"),
    ),
    "United States": Locale(
        ("James", "Maria", "Chris", "Ashley", "David", "Emily"),
        ("Johnson", "Williams", "Brown", "Garcia", "Miller", "Davis"),
        ("Grocery", "Pharmacy", "Diner", "Gas Station", "Hardware"),
        ("Starbucks", "Amazon", "Walmart", "Uber", "Target", "Costco"),
    ),
    "UAE": Locale(
        ("Omar", "Fatima", "Hassan", "Layla", "Yusuf", "Noor"),
        ("Al Maktoum", "Al Nahyan", "Khan", "Rahman", "Hassan", "Ali"),
        ("Supermarket", "Pharmacy", "Cafe", "Electronics", "Salon"),
        ("Carrefour", "ADNOC", "Noon", "LuLu", "Careem", "Spinneys"),
    ),
    "Saudi Arabia": Locale(
        ("Fahad", "Aisha", "Majid", "Huda", "Sultan", "Noura"),
        ("Al Saud", "Al Harbi", "Al Otaibi", "Al Qahtani", "Al Ghamdi"),
        ("Pharmacy", "Bakery", "Market", "Fuel Station"),
        ("Panda", "Jarir", "STC", "Tamimi", "HungerStation"),
    ),
    "Ethiopia": Locale(
        ("Abebe", "Mekdes", "Dawit", "Hanna", "Yonas", "Selam"),
        ("Bekele", "Tesfaye", "Haile", "Alemu", "Kebede"),
        ("Mini Market", "Cafe", "Pharmacy", "Taxi Stand"),
        ("Ethio Telecom", "Dashen Super", "Abyssinia"),
    ),
    "Tanzania": Locale(
        ("Juma", "Amina", "Baraka", "Neema", "Hassani"),
        ("Mwangi", "Ngowi", "Kimaro", "Mushi", "Lyimo"),
        ("Duka", "Pharmacy", "Cafe", "Market"),
        ("Vodacom", "Shoppers", "Azam"),
    ),
    "Nigeria": Locale(
        ("Chinedu", "Aisha", "Tunde", "Ngozi", "Emeka", "Blessing"),
        ("Okafor", "Adeyemi", "Balogun", "Nwachukwu", "Ibrahim"),
        ("Market", "Pharmacy", "POS Agent", "Restaurant"),
        ("Jumia", "GTBank Transfer", "DSTV", "Uber NG"),
    ),
    "Nepal": Locale(
        ("Suman", "Anita", "Bikash", "Sita", "Ramesh"),
        ("Shrestha", "Gurung", "Tamang", "Adhikari", "Karki"),
        ("Pasal", "Pharmacy", "Cafe", "Mart"),
        ("eSewa", "Khalti", "Bhatbhateni"),
    ),
    "Egypt": Locale(
        ("Omar", "Mona", "Karim", "Yasmin", "Hassan"),
        ("Hassan", "Ibrahim", "Farouk", "Saleh", "Nour"),
        ("Pharmacy", "Cafe", "Market", "Fuel Station"),
        ("Fawry", "Carrefour EG", "Uber EG"),
    ),
    "Kenya": Locale(
        ("Kamau", "Wanjiku", "Otieno", "Achieng", "Mwangi"),
        ("Omondi", "Njeri", "Kipchoge", "Wambui", "Odhiambo"),
        ("Duka", "Pharmacy", "Kiosk", "Matatu"),
        ("Safaricom", "Naivas", "Java House", "Uber KE"),
    ),
    "Bangladesh": Locale(
        ("Rahim", "Fatema", "Karim", "Nusrat", "Hasan"),
        ("Rahman", "Ahmed", "Chowdhury", "Islam", "Hossain"),
        ("Dokan", "Pharmacy", "Cafe"),
        ("bKash Agent", "Grameenphone", "Unimart"),
    ),
    "Oman": Locale(
        ("Said", "Amal", "Nasser", "Maryam", "Khalid"),
        ("Al Busaidi", "Al Balushi", "Al Hinai", "Al Zadjali"),
        ("Pharmacy", "Cafe", "Hypermarket"),
        ("Ooredoo", "Carrefour OM", "Shell Oman"),
    ),
    "Pakistan": Locale(
        ("Ali", "Ayesha", "Bilal", "Hina", "Usman"),
        ("Khan", "Malik", "Sheikh", "Raza", "Qureshi"),
        ("General Store", "Pharmacy", "Cafe"),
        ("JazzCash", "Daraz", "PSO"),
    ),
    "Sri Lanka": Locale(
        ("Nimal", "Sanduni", "Kasun", "Ishara", "Tharindu"),
        ("Perera", "Fernando", "Silva", "Jayawardena"),
        ("Pharmacy", "Cafe", "Grocery"),
        ("Dialog", "Keells", "PickMe"),
    ),
    "Turkey": Locale(
        ("Mehmet", "Ayse", "Emre", "Elif", "Can"),
        ("Yilmaz", "Demir", "Kaya", "Celik", "Sahin"),
        ("Market", "Eczane", "Cafe"),
        ("BIM", "A101", "Trendyol"),
    ),
    "Russia": Locale(
        ("Ivan", "Anna", "Dmitry", "Olga", "Sergei"),
        ("Petrov", "Ivanov", "Smirnov", "Volkov"),
        ("Magazin", "Apteka", "Kafe"),
        ("Wildberries", "Yandex", "Ozon"),
    ),
    "Czech Republic": Locale(
        ("Jan", "Petra", "Tomas", "Eva", "Lukas"),
        ("Novak", "Svoboda", "Dvorak", "Prochazka"),
        ("Obchod", "Lekarna", "Kavarna"),
        ("Lidl", "Albert", "Alza"),
    ),
    "Eurozone": Locale(
        ("Hans", "Anna", "Pierre", "Marie", "Luca"),
        ("Mueller", "Schmidt", "Dupont", "Rossi"),
        ("Markt", "Apotheke", "Cafe"),
        ("Rewe", "Carrefour", "Lidl"),
    ),
    "Mozambique": Locale(
        ("Joao", "Maria", "Carlos", "Ana", "Pedro"),
        ("Santos", "Ferreira", "Costa", "Machel"),
        ("Loja", "Farmacia", "Cafe"),
        ("MCel", "Shoprite", "Vodacom MZ"),
    ),
}

AMOUNT_RANGE: dict[str, tuple[float, float]] = {
    "INR": (20, 80_000),
    "USD": (4, 2_400),
    "AED": (8, 7_000),
    "SAR": (10, 6_000),
    "ETB": (80, 60_000),
    "TZS": (2_000, 1_500_000),
    "NGN": (400, 400_000),
    "NPR": (100, 70_000),
    "EGP": (40, 18_000),
    "KES": (40, 70_000),
    "BDT": (50, 25_000),
    "OMR": (1.5, 350),
    "PKR": (200, 180_000),
    "LKR": (200, 90_000),
    "TRY": (40, 25_000),
    "RUB": (200, 80_000),
    "CZK": (80, 25_000),
    "EUR": (5, 2_500),
    "MZN": (40, 15_000),
}

PREFIXES = ("AD", "AX", "BT", "BV", "JK", "JX", "TX", "VM", "BZ")

TEMPLATES: tuple[Template, ...] = (
    Template("ind_sent", "Indian Bank", "India", "INR", "INDBNK-S", "debit",
             "Sent Rs.{amount} from A/c *{last4} on {date_dmy} to {merchant}."
             "RRN {rrn}.Avl Bal Rs.{balance}.Not you?SMS BLOCK to 9444412345-Indian Bank",
             ("amount", "last4", "merchant", "reference", "balance"), expense_type="transfer"),
    Template("ind_debited", "Indian Bank", "India", "INR", "INDBNK-S", "debit",
             "A/c *{last4} debited Rs.{amount} on {date_dmy} to {merchant}."
             "RRN {rrn}. Bal: Rs.{balance}-Indian Bank",
             ("amount", "last4", "merchant", "reference", "balance"), expense_type="transfer"),
    Template("ind_credited", "Indian Bank", "India", "INR", "INDBNK-S", "credit",
             "Rs.{amount} credited to A/c *{last4} on {date_dmy} from {merchant}."
             "UPI:{rrn}.Available Balance: Rs.{balance}-Indian Bank",
             ("amount", "last4", "merchant", "reference", "balance"), expense_type="income"),
    Template("sbi_debit", "State Bank of India", "India", "INR", "SBIBK-S", "debit",
             "Dear SBI User, your A/c XX{last4} has been debited by {amount} on {date_dmy} "
             "trf to {merchant} Ref {rrn}. Avl Bal Rs.{balance}-SBI",
             ("amount", "last4", "merchant", "balance"), expense_type="transfer"),
    Template("sbi_credit", "State Bank of India", "India", "INR", "SBIBK-S", "credit",
             "Rs.{amount} has been credited to A/c XX{last4} on {date_dmy} "
             "transfer from {merchant} Ref {rrn}. Avl Bal Rs.{balance}-SBI",
             ("amount", "last4", "merchant", "balance"), expense_type="income"),
    Template("sbi_spent", "State Bank of India", "India", "INR", "SBIBK-S", "debit",
             "Rs.{amount} spent on card ending {last4} at {merchant} on {date_dmy}. "
             "Your available limit is Rs.{balance}-SBI",
             ("amount", "last4", "merchant", "balance"), expense_type="shopping"),
    Template("axis_spent", "Axis Bank", "India", "INR", "AXISBK-S", "debit",
             "Spent INR {amount}\nAxis Bank Card no. XX{last4}\n"
             "{date_dmy} {time} IST\n{merchant}\nAvl Limit: INR {balance}\n"
             "Not you? SMS BLOCK {last4} to 56161510",
             ("last4", "merchant", "balance"), expense_type="shopping"),
    Template("axis_upi_debit", "Axis Bank", "India", "INR", "AXISBK-S", "debit",
             "INR {amount} debited from A/c no. XX{last4} on {date_dmy}. "
             "UPI/P2M/{rrn}/{merchant} Not you? SMS BLOCK to 56161510",
             ("amount", "last4", "merchant", "reference"), expense_type="transfer"),
    Template("axis_credit", "Axis Bank", "India", "INR", "AXISBK-S", "credit",
             "INR {amount} credited to A/c no. XX{last4} on {date_dmy}. "
             "Info - {merchant}. Chk SMS. Avl Lmt INR {balance}",
             ("amount", "last4"), expense_type="income"),
    Template("icici_debit", "ICICI Bank", "India", "INR", "ICICIB-S", "debit",
             "Acct XX{last4} is debited with Rs.{amount} on {date_mon} at {merchant}. "
             "Avl Bal Rs.{balance}. UPI:{rrn}-ICICI Bank",
             ("amount", "last4", "balance", "reference"), expense_type="transfer"),
    Template("icici_credit", "ICICI Bank", "India", "INR", "ICICIB-S", "credit",
             "Acct XX{last4} is credited with Rs.{amount} on {date_mon} from {merchant}. "
             "Available Balance is Rs.{balance}. UPI:{rrn}-ICICI Bank",
             ("amount", "last4", "balance", "reference"), expense_type="income"),
    Template("icici_spent", "ICICI Bank", "India", "INR", "ICICIB-S", "debit",
             "INR {amount} spent on ICICI Bank Card XX{last4} on {date_mon} at {merchant}. "
             "Avl Bal Rs.{balance}-ICICI Bank",
             ("amount", "last4", "balance"), expense_type="shopping"),
    Template("hdfc_debit", "HDFC Bank", "India", "INR", "HDFCBK-S", "debit",
             "Rs.{amount} debited from HDFC Bank XX{last4} towards {merchant} on {date_mon}. "
             "Avl bal: INR {balance}",
             ("amount", "last4", "merchant", "balance"), expense_type="transfer"),
    Template("hdfc_upi", "HDFC Bank", "India", "INR", "HDFCBK-S", "debit",
             "INR {amount} debited from HDFC Bank XX{last4} To {merchant} UPI on {date_dmy4}. "
             "Avl bal: INR {balance}",
             ("amount", "last4", "merchant", "balance"), expense_type="transfer"),
    Template("boi_debit", "Bank of India", "India", "INR", "BOIIND-S", "debit",
             "Rs.{amount} debited from A/c XX{last4} towards {merchant} via UPI, "
             "Ref No. {rrn}. Avl Bal: Rs.{balance}-BOI",
             ("amount", "last4", "merchant", "reference", "balance"), expense_type="transfer"),
    Template("boi_credit", "Bank of India", "India", "INR", "BOIIND-S", "credit",
             "Rs.{amount} credited to A/c XX{last4} from {merchant} via UPI, "
             "Ref No. {rrn}. Available Balance: Rs.{balance}-BOI",
             ("amount", "last4", "merchant", "reference", "balance"), expense_type="income"),
    Template("chase_purchase", "Chase", "United States", "USD", "CHASE-S", "debit",
             "Chase: A ${amount} purchase at {merchant} on {date_us} with card ending in {last4}.",
             ("amount", "merchant", "last4"), expense_type="shopping"),
    Template("citi_txn", "Citi Bank", "United States", "USD", "CITI-S", "debit",
             "A ${amount} transaction was made at {merchant} on card ending in {last4}.",
             ("amount", "merchant", "last4"), expense_type="shopping"),
    Template("discover_txn", "Discover Card", "United States", "USD", "DISCOVER-S", "debit",
             "A transaction of ${amount} at {merchant} on {date_us}.",
             ("amount", "merchant"), expense_type="shopping"),
    Template("schwab_debit", "Charles Schwab", "United States", "USD", "SCHWAB-S", "debit",
             "A ${amount} debit card transaction from account ending {last4}.",
             ("amount", "last4"), expense_type="unknown"),
    Template("adcb_dr", "Abu Dhabi Commercial Bank", "UAE", "AED", "ADCB-S", "debit",
             "Dr. transaction of AED {amount} in your account XX{last4} at {merchant}, AE. "
             "Avl.Bal AED {balance}",
             ("amount", "last4", "merchant", "balance"), expense_type="unknown"),
    Template("enbd_spent", "Emirates NBD", "UAE", "AED", "ENBD-S", "debit",
             "Purchase at {merchant}. Avl Bal AED {balance} card xxxx{last4}",
             ("last4", "merchant", "balance"), expense_type="shopping"),
    Template("liv_purchase", "Liv Bank", "UAE", "AED", "LIV-S", "debit",
             "purchase of AED {amount} at {merchant} Avl Balance is AED {balance} "
             "Debit Card ending {last4}",
             ("last4", "merchant", "balance"), expense_type="shopping"),
    Template("mashreq_purchase", "Mashreq Bank", "UAE", "AED", "MASHREQ-S", "debit",
             "Purchase for AED {amount} at {merchant} on {date_mash}. "
             "Card ending {last4}. Available Balance is AED {balance}",
             ("last4", "merchant", "balance"), expense_type="shopping"),
    Template("rajhi_purchase", "Al Rajhi Bank", "Saudi Arabia", "SAR", "RAJHI-S", "debit",
             "Purchase\nAmount: SAR {amount}\nAt: {merchant}",
             ("amount", "merchant"), expense_type="shopping"),
    Template("cbe_debit", "Commercial Bank of Ethiopia", "Ethiopia", "ETB", "CBE-S", "debit",
             "Your account {last4} has been debited for {merchant} with ETB {amount}. "
             "Your Current Balance is ETB {balance}. Ref No {rrn}",
             ("amount", "merchant", "balance", "reference"), expense_type="unknown"),
    Template("awash_credit", "Awash Bank", "Ethiopia", "ETB", "AWASH-S", "credit",
             "ETB {amount} has been credited from {merchant} on: {date_slash}. "
             "Balance is ETB {balance} Txn ID: {rrn}",
             ("amount", "balance", "reference"), expense_type="income"),
    Template("telebirr_pay", "Telebirr", "Ethiopia", "ETB", "TELEBIRR-S", "debit",
             "paid ETB {amount} to {merchant} on {date_slash}. "
             "Your telebirr account balance is ETB {balance} transaction number is {rrn}",
             ("amount", "merchant", "balance", "reference"), expense_type="transfer"),
    Template("crdb_paid", "CRDB Bank", "Tanzania", "TZS", "CRDB-S", "debit",
             "Paid: {merchant} TZS {amount} Card: {last4} Balance is TZS {balance}",
             ("amount", "merchant", "last4", "balance"), expense_type="shopping"),
    Template("zenith_dr", "Zenith Bank", "Nigeria", "NGN", "ZENITH-S", "debit",
             "Acct:******{last4}\nDR Amt:{amount}\nDesc:{merchant}\nBal:{balance}",
             ("amount", "last4", "balance"), expense_type="unknown"),
    Template("access_debit", "Access Bank", "Nigeria", "NGN", "ACCESS-S", "debit",
             "debit\nAmt: NGN {amount}\nAcc: ****{last4}\nDesc: {merchant}\nAvail Bal: NGN {balance}",
             ("amount", "last4", "balance"), expense_type="unknown"),
    Template("opay_debit", "Opay", "Nigeria", "NGN", "OPAY-S", "debit",
             "Dear OPay user, N {amount} has been debited for {merchant} on {date_mon}",
             ("amount", "merchant"), expense_type="unknown"),
    Template("nabil_debit", "Nabil Bank", "Nepal", "NPR", "NABIL-S", "debit",
             "NPR {amount} debited from A/c #{last4} Remarks: SHOP MTXN{rrn}",
             ("amount", "last4", "reference"), expense_type="unknown"),
    Template("nbl_credit", "Nepal Bank Limited", "Nepal", "NPR", "NBL-S", "credit",
             "NPR {amount} credited #{last4} {time}, {merchant}",
             ("amount", "last4", "merchant"), expense_type="income", one_word_merchant=True),
    Template("cib_spent", "CIB Egypt", "Egypt", "EGP", "CIB-S", "debit",
             "Purchase for EGP {amount} at {merchant} on {date_day_mon} with credit card #{last4}. "
             "available limit is EGP {balance}",
             ("amount", "merchant", "last4", "balance"), expense_type="shopping"),
    Template("mpesa_paid", "M-PESA", "Kenya", "KES", "MPESA-S", "debit",
             "{rrn10} Confirmed. Ksh{amount} paid to {merchant} 254. on {date_slash}. "
             "New M-PESA balance is Ksh{balance}",
             ("amount", "merchant", "balance", "reference"), expense_type="transfer"),
    Template("bkash_pay", "bKash", "Bangladesh", "BDT", "BKASH-S", "debit",
             "Tk {amount} sent. Balance Tk {balance} TrxID {rrn10}",
             ("amount", "balance", "reference"), expense_type="transfer"),
    Template("muscat_debit", "Bank Muscat", "Oman", "OMR", "MUSCAT-S", "debit",
             "OMR {amount} debited from your card. رصيدك الحالي هو {balance} OMR",
             ("amount", "balance"), expense_type="unknown"),
    Template("faysal_purchase", "Faysal Bank", "Pakistan", "PKR", "FAYSAL-S", "debit",
             "PKR {amount} debit card purchase at {merchant} from FBL A/C ****{last4} Ref {rrn}",
             ("amount", "merchant", "last4", "reference"), expense_type="shopping"),
    Template("sampath_debit", "Sampath Bank", "Sri Lanka", "LKR", "SAMPATH-S", "debit",
             "LKR {amount} debited from AC ***{last4} at {merchant} Avl Bal LKR {balance}",
             ("amount", "last4", "merchant", "balance"), expense_type="shopping"),
    # extra types on existing banks
    Template("ind_atm", "Indian Bank", "India", "INR", "INDBNK-S", "atm",
             "A/c *{last4} withdrawn Rs.{amount} ATM at {merchant} on {date_dmy}. "
             "Bal: Rs.{balance}-Indian Bank",
             ("amount", "last4", "merchant", "balance"), expense_type="cash"),
    Template("ind_upi_pay", "Indian Bank", "India", "INR", "INDBNK-S", "debit",
             "UPI payment of Rs.{amount} from A/c *{last4} to {merchant}.UPI:{rrn} "
             "Available Balance: Rs.{balance}-Indian Bank",
             ("amount", "last4", "merchant", "reference", "balance"), expense_type="transfer"),
    Template("sbi_atm", "State Bank of India", "India", "INR", "SBIBK-S", "atm",
             "ATM withdrawal of Rs.{amount} at {merchant} on {date_dmy} A/c XX{last4}. "
             "Avl Bal Rs.{balance}-SBI",
             ("amount", "last4", "merchant", "balance"), expense_type="cash"),
    Template("sbi_upi", "State Bank of India", "India", "INR", "SBIBK-S", "debit",
             "paid to {upi} Rs.{amount} A/c XX{last4} Avl Bal Rs.{balance}-SBI",
             ("amount", "last4", "balance"), expense_type="transfer"),
    Template("hdfc_neft_cr", "HDFC Bank", "India", "INR", "HDFCBK-S", "credit",
             "NEFT Cr-SBIN0001234-{merchant} INR {amount} Avl bal: INR {balance}",
             ("amount", "merchant", "balance"), expense_type="income"),
    Template("axis_payment", "Axis Bank", "India", "INR", "AXISBK-S", "debit",
             "Payment of INR {amount} from A/c no. XX{last4} on {date_dmy}",
             ("amount", "last4"), expense_type="bills"),
    Template("mpesa_received", "M-PESA", "Kenya", "KES", "MPESA-S", "credit",
             "{rrn10} Confirmed. You have received Ksh{amount} from {merchant} on {date_slash}. "
             "New M-PESA balance is Ksh{balance}",
             ("amount", "merchant", "balance", "reference"), expense_type="income"),
    Template("adcb_atm", "Abu Dhabi Commercial Bank", "UAE", "AED", "ADCB-S", "atm",
             "AED {amount} withdrawn from acc. XX{last4}. Avl.Bal AED {balance}",
             ("amount", "last4", "balance"), expense_type="cash"),
    Template("schwab_atm", "Charles Schwab", "United States", "USD", "SCHWAB-S", "atm",
             "A ${amount} ATM transaction from account ending {last4}.",
             ("amount", "last4"), expense_type="cash"),
    Template("access_credit", "Access Bank", "Nigeria", "NGN", "ACCESS-S", "credit",
             "credit\nAmt: NGN {amount}\nAcc: ****{last4}\nDesc: {merchant}\nAvail Bal: NGN {balance}",
             ("amount", "last4", "balance"), expense_type="income"),
    Template("zenith_cr", "Zenith Bank", "Nigeria", "NGN", "ZENITH-S", "credit",
             "Acct:******{last4}\nCR Amt:{amount}\nDesc:{merchant}\nBal:{balance}",
             ("amount", "last4", "balance"), expense_type="income"),
    # more India banks
    Template("pnb_debit", "Punjab National Bank", "India", "INR", "PNBBNK-S", "debit",
             "A/c XX{last4} debited with Rs.{amount} towards {merchant} for Rs.{amount}. "
             "UPI Ref ID:{rrn} Avl Bal Rs.{balance}",
             ("amount", "last4", "merchant", "reference", "balance"), expense_type="transfer"),
    Template("pnb_credit", "Punjab National Bank", "India", "INR", "PNBBNK-S", "credit",
             "Rs.{amount} credited to A/c XX{last4} UPI:{rrn} Avl Bal Rs.{balance}",
             ("amount", "last4", "reference", "balance"), expense_type="income"),
    Template("bob_spent", "Bank of Baroda", "India", "INR", "BOB-S", "debit",
             "ALERT: INR {amount} is spent on BOBCARD ending {last4}. AvlBal: Rs.{balance} Ref:{rrn}",
             ("amount", "last4", "balance", "reference"), expense_type="shopping"),
    Template("bob_credit", "Bank of Baroda", "India", "INR", "BOB-S", "credit",
             "Rs.{amount} Credited to A/c XX{last4} IMPS/{rrn} by {merchant}. AvlBal: Rs.{balance}",
             ("amount", "last4", "merchant", "reference", "balance"), expense_type="income"),
    Template("federal_spent", "Federal Bank", "India", "INR", "FEDBNK-S", "debit",
             "INR {amount} spent at {merchant} on {date_slash} on your Federal Bank Debit Card {last4}",
             ("amount", "merchant", "last4"), expense_type="shopping"),
    Template("federal_received", "Federal Bank", "India", "INR", "FEDBNK-S", "credit",
             "you've received INR {amount} It was sent by {merchant} on {date_dmy} A/c XX{last4}",
             ("amount", "merchant", "last4"), expense_type="income"),
    Template("idfc_debit", "IDFC First Bank", "India", "INR", "IDFCFB-S", "debit",
             "Debit Rs.{amount} A/C XX{last4} at {merchant} on {date_dmy} New Bal : INR {balance} UPI:{rrn}",
             ("amount", "last4", "merchant", "balance", "reference"), expense_type="shopping", one_word_merchant=False, merchant_upper=True),
    Template("idfc_credit", "IDFC First Bank", "India", "INR", "IDFCFB-S", "credit",
             "A/C XX{last4} credited by Rs.{amount} from {merchant} New balance is INR {balance} IMPS Ref no {rrn}",
             ("amount", "last4", "balance", "reference"), expense_type="income"),
    Template("indus_debit", "IndusInd Bank", "India", "INR", "INDUSB-S", "debit",
             "INR {amount} debited from IndusInd Account XX{last4} towards {merchant} "
             "Avl BAL of INR {balance} RRN:{rrn}",
             ("amount", "last4", "merchant", "balance", "reference"), expense_type="transfer", one_word_merchant=True),
    Template("union_debit", "Union Bank of India", "India", "INR", "UNIONB-S", "debit",
             "Rs.{amount} debited from A/C *{last4} to {merchant} on {date_dmy} "
             "ref no {rrn} Avl Bal Rs.{balance}",
             ("amount", "last4", "merchant", "reference", "balance"), expense_type="transfer"),
    Template("canara_debit", "Canara Bank", "India", "INR", "CANBNK-S", "debit",
             "INR {amount} has been DEBITED to {merchant}, UPI Ref {rrn} account XX{last4} "
             "Avail.bal INR {balance}-Canara",
             ("amount", "merchant", "reference", "last4", "balance"), expense_type="transfer"),
    # US / Gulf / Africa / wallets
    Template("navy_approved", "Navy Federal Credit Union", "United States", "USD", "NFCU-S", "debit",
             "Transaction for ${amount} was approved on debit card {last4} at {merchant} at {time_hm}",
             ("amount", "last4", "merchant"), expense_type="shopping"),
    Template("huntington_wd", "Huntington Bank", "United States", "USD", "HUNTINGTON-S", "atm",
             "withdrawal: ${amount} at {merchant}. Acct CK{last4}",
             ("amount", "merchant", "last4"), expense_type="cash"),
    Template("stc_pay", "STC Bank", "Saudi Arabia", "SAR", "STCBANK-S", "debit",
             "Amount: {amount} SAR\nFrom: {merchant}\nVia: {last4}",
             ("amount", "merchant", "last4"), expense_type="unknown"),
    Template("ei_purchase", "Emirates Islamic", "UAE", "AED", "EIB-S", "debit",
             "At: {merchant}\nCard Ending: {last4}\nAvailable Balance: AED {balance}",
             ("merchant", "last4", "balance"), expense_type="shopping"),
    Template("sabb_ar", "SABB", "Saudi Arabia", "SAR", "SABB-S", "debit",
             "مبلغ: SAR {amount}\nلدى: {merchant}\nبطاقة: ****{last4}\nالرصيد المتاح: SAR {balance}",
             ("amount", "merchant", "last4", "balance"), expense_type="shopping"),
    Template("alinma_ar", "Alinma Bank", "Saudi Arabia", "SAR", "ALINMA-S", "debit",
             "بمبلغ: {amount} SAR\nلدى: {merchant}\nحساب: ****{last4}\nالرصيد: {balance} SAR",
             ("amount", "merchant", "last4", "balance"), expense_type="shopping"),
    Template("moniepoint_dr", "Moniepoint", "Nigeria", "NGN", "MONIE-S", "debit",
             "Debit Alert\nAmt: NGN {amount}\nAcc: {last4}\nDesc: {merchant}\nBal: NGN {balance}",
             ("amount", "last4", "balance"), expense_type="unknown"),
    Template("keystone_dr", "Keystone Bank", "Nigeria", "NGN", "KEYSTN-S", "debit",
             "debit!\nAmt: NGN {amount}\nAcct: ****{last4}\nDesc: {merchant}\nBal: NGN {balance}",
             ("amount", "last4", "balance"), expense_type="unknown"),
    Template("jaiz_dr", "Jaiz Bank", "Nigeria", "NGN", "JAIZBK-S", "debit",
             "Amt: N {amount} DR\nAcct: ****{last4}\nDesc: {merchant}\nBal: N {balance}",
             ("amount", "last4", "balance"), expense_type="unknown"),
    Template("everest_dr", "Everest Bank", "Nepal", "NPR", "EVEREST-S", "debit",
             "A/c XX{last4} debited by NPR {amount} For: {merchant}. {rrn}",
             ("amount", "last4", "merchant", "reference"), expense_type="unknown"),
    Template("nmb_np", "NMB Bank", "Nepal", "NPR", "NMBNP-S", "debit",
             "NPR {amount} at {merchant} on {date_dmy} A/C {last4} Ref: {rrn}",
             ("amount", "merchant", "last4", "reference"), expense_type="shopping"),
    Template("arab_egp", "Arab Bank", "Egypt", "EGP", "ARABBK-S", "debit",
             "Purchase from {merchant} for EGP {amount} Card {last4}. Available balance is EGP {balance}",
             ("amount", "merchant", "last4", "balance"), expense_type="shopping"),
    Template("tigo_sent", "Tigo Pesa", "Tanzania", "TZS", "TIGOPESA-S", "debit",
             "You have sent TSh {amount} to 255700 - {merchant}. New balance is TSh {balance} TxnId: {rrn}",
             ("amount", "merchant", "balance", "reference"), expense_type="transfer"),
    Template("tigo_recv", "Tigo Pesa", "Tanzania", "TZS", "TIGOPESA-S", "credit",
             "You have received TSh {amount} from {merchant}. New balance is TSh {balance} TxnId: {rrn}",
             ("amount", "balance", "reference"), expense_type="income"),
    Template("dashen_cr", "Dashen Bank", "Ethiopia", "ETB", "DASHEN-S", "credit",
             "ETB {amount} credited from {merchant} on on {date_slash}. "
             "Your current balance is ETB {balance} Ref No:{rrn}",
             ("amount", "balance", "reference"), expense_type="income", one_word_merchant=False, merchant_upper=True),
    Template("zemen_pos", "Zemen Bank", "Ethiopia", "ETB", "ZEMENBANK-S", "debit",
             "pos purchase transaction at {merchant} on {date_dmon4} ETB {amount}. "
             "Your Current Balance is ETB {balance} with reference {rrn}",
             ("amount", "merchant", "balance", "reference"), expense_type="shopping"),
    Template("enpara_spend", "Enpara", "Turkey", "TRY", "ENPARA-S", "debit",
             "{amount} TL tutarında harcama yapıldı tarihinde 12 - {merchant} firmasında "
             "bağlı {last4} ile biten Encard",
             ("amount", "merchant", "last4"), expense_type="shopping"),
    Template("tbank_spend", "T-Bank", "Russia", "RUB", "TBANK-S", "debit",
             "{amount} ₽. {merchant}. Доступно {balance} ₽ *{last4}",
             ("amount", "merchant", "balance", "last4"), expense_type="shopping"),
    Template("mbank_cz", "mBank CZ", "Czech Republic", "CZK", "MBANK-S", "debit",
             "{amount} CZK v obchodě {merchant}.",
             ("amount", "merchant"), expense_type="shopping"),
    Template("sparkasse_eur", "Sparkasse Rhein-Maas", "Eurozone", "EUR", "SPARKASSE-S", "debit",
             "{amount} EUR Neuer Saldo: {balance} EUR Konto ***{last4}",
             ("amount", "balance", "last4"), expense_type="unknown"),
    Template("bpce_eur", "BPCE", "Eurozone", "EUR", "BPCE-S", "debit",
             "debit de {amount} EUR vers {merchant}",
             ("amount", "merchant"), expense_type="transfer"),
    Template("mpesa_moz", "M-Pesa Mozambique", "Mozambique", "MZN", "MPESAMZ-S", "debit",
             "Confirmado {rrn10} Transferiste {amount} MT para 84X - {merchant} aos {date_slash}. "
             "novo saldo M-Pesa e de {balance} MT",
             ("amount", "merchant", "balance", "reference"), expense_type="transfer"),
    Template("ndb_debit", "National Development Bank", "Sri Lanka", "LKR", "NDBSL-S", "debit",
             "LKR {amount} debited at {merchant}. Avl Bal {balance} AC XXXX{last4}",
             ("amount", "merchant", "balance", "last4"), expense_type="shopping"),
    Template("ntb_card", "Nations Trust Bank", "Sri Lanka", "LKR", "NTBSL-S", "debit",
             "for LKR {amount} at {merchant} Available Bal LKR {balance} Card 1234**{last4}",
             ("amount", "merchant", "balance", "last4"), expense_type="shopping"),
    # ---- rich English variety: real-world phrasing (Pennywise-backed) ----
    Template("kotak_upi_debit", "Kotak Bank", "India", "INR", "KOTAKB-S", "debit",
             "From A/c XX{last4} Rs.{amount} transferred to {upi} ({merchant}) on {date_dmy} UPI Ref {rrn}. Avl Bal Rs.{balance}-Kotak Bank",
             (), expense_type="transfer"),
    Template("kotak_upi_credit", "Kotak Bank", "India", "INR", "KOTAKB-S", "credit",
             "Rs.{amount} credited to A/c XX{last4} on {date_dmy} from {merchant} ({upi}) Ref {rrn}. Avl Bal Rs.{balance}-Kotak",
             (), expense_type="income"),
    Template("kotak_spent", "Kotak Bank", "India", "INR", "KOTAKB-S", "debit",
             "INR {amount} spent on Kotak Card XX{last4} at {merchant} on {date_mon}. Avl Bal Rs.{balance}",
             (), expense_type="shopping"),
    Template("yesbank_spent", "Yes Bank", "India", "INR", "YESBNK-S", "debit",
             "INR {amount} spent from YES BANK Card {last4} at {merchant} on {date_dmy}. Avl Limit Rs.{balance}-YES BANK",
             (), expense_type="shopping"),
    Template("yesbank_upi", "Yes Bank", "India", "INR", "YESBNK-S", "debit",
             "UPI P2M {amount} debited from A/c XX{last4} to VPA {upi} @UPI_{merchant} on {date_dmy}-YES BANK",
             (), expense_type="transfer"),
    Template("hsbc_debit", "HSBC Bank", "India", "INR", "HSBC-S", "debit",
             "HSBC: INR {amount} debited from A/c XX{last4} on {date_dmy} at {merchant}. Ref {rrn}. Bal INR {balance}-HSBC",
             (), expense_type="transfer"),
    Template("hsbc_credit", "HSBC Bank", "India", "INR", "HSBC-S", "credit",
             "HSBC: INR {amount} credited to A/c XX{last4} on {date_dmy} from {merchant}. Ref {rrn}. Bal INR {balance}-HSBC",
             (), expense_type="income"),
    Template("hsbc_card", "HSBC Bank", "India", "INR", "HSBC-S", "debit",
             "HSBC Card XX{last4} used for INR {amount} on {date_mon} at {merchant}. Avl Bal INR {balance}",
             (), expense_type="shopping"),
    Template("scb_debit", "Standard Chartered Bank", "India", "INR", "SCBANK-S", "debit",
             "SCB A/c XX{last4} is debited for Rs. {amount} on {date_dmy} towards {merchant}. Ref {rrn}. Avl Bal Rs.{balance}",
             (), expense_type="transfer"),
    Template("scb_credit", "Standard Chartered Bank", "India", "INR", "SCBANK-S", "credit",
             "SCB A/c XX{last4} is credited for Rs. {amount} on {date_dmy} from {merchant}. Avl Bal Rs.{balance}",
             (), expense_type="income"),
    Template("jkb_debit", "JK Bank", "India", "INR", "JKBANK-S", "debit",
             "Your J&K Bank A/c XX{last4} debited Rs.{amount} on {date_dmy} for {merchant} (UPI Ref {rrn}) Avl Bal Rs.{balance}",
             (), expense_type="transfer"),
    Template("jkb_upi", "JK Bank", "India", "INR", "JKBANK-S", "debit",
             "JKB: Rs.{amount} debited via UPI to {merchant} VPA {upi} on {date_dmy} Ref {rrn}. Bal Rs.{balance}",
             (), expense_type="transfer"),
    Template("fab_debit", "First Abu Dhabi Bank", "UAE", "AED", "FAB-S", "debit",
             "FAB: Amount AED {amount} debited from A/c *{last4} on {date_dmy} at {merchant}. Available Balance AED {balance}",
             (), expense_type="transfer"),
    Template("fab_credit", "First Abu Dhabi Bank", "UAE", "AED", "FAB-S", "credit",
             "FAB: Amount AED {amount} credited to A/c *{last4} on {date_dmy} from {merchant}. Bal AED {balance}",
             (), expense_type="income"),
    Template("ausf_debit", "AU Small Finance Bank", "India", "INR", "AUSF-S", "debit",
             "AU Bank A/c XX{last4} debited INR {amount} on {date_dmy} for {merchant}. Avl Bal INR {balance}-AU Bank",
             (), expense_type="transfer"),
    Template("ausf_credit", "AU Small Finance Bank", "India", "INR", "AUSF-S", "credit",
             "AU Bank A/c XX{last4} credited INR {amount} on {date_dmy} from {merchant}. Avl Bal INR {balance}-AU Bank",
             (), expense_type="income"),
    Template("sib_debit", "South Indian Bank", "India", "INR", "SIB-S", "debit",
             "Rs. {amount} debited from A/c XX{last4} on {date_dmy} Info: UPI/DR/{rrn}/{merchant} on {date_dmy}. Avl Bal Rs.{balance}-SIB",
             (), expense_type="transfer"),
    Template("sib_credit", "South Indian Bank", "India", "INR", "SIB-S", "credit",
             "Rs. {amount} credited to A/c XX{last4} on {date_dmy} Info: UPI/CR/{rrn}/{merchant}. Avl Bal Rs.{balance}-SIB",
             (), expense_type="income"),
    Template("central_debit", "Central Bank of India", "India", "INR", "CENTBK-S", "debit",
             "Central Bank A/c XX{last4} Debited by Rs. {amount} on {date_dmy} at {merchant}. AL: Rs.{balance}",
             (), expense_type="transfer"),
    Template("uco_debit", "UCO Bank", "India", "INR", "UCOBNK-S", "debit",
             "UCO Bank A/c XX{last4} debited Rs.{amount} on {date_dmy} to {merchant} via UPI Ref {rrn}. Bal Rs.{balance}",
             (), expense_type="transfer"),
    Template("iob_credit", "Indian Overseas Bank", "India", "INR", "IOB-S", "credit",
             "Your IOB A/c XX{last4} credited with Rs. {amount} on {date_dmy} from {merchant}. Avl Bal Rs.{balance}",
             (), expense_type="income"),
    Template("mpesa_tz_send", "M-Pesa Tanzania", "Tanzania", "TZS", "MPTZ-S", "debit",
             "You have sent TZS {amount} to {merchant} on {date_slash}. New balance TZS {balance} TxnID {rrn}-M-Pesa Tanzania",
             (), expense_type="transfer"),
    Template("mpesa_tz_recv", "M-Pesa Tanzania", "Tanzania", "TZS", "MPTZ-S", "credit",
             "You have received TZS {amount} from {merchant} on {date_slash}. New balance TZS {balance} TxnID {rrn}-M-Pesa Tanzania",
             (), expense_type="income"),
    Template("chase_alt", "Chase", "United States", "USD", "CHASE-S", "debit",
             "Chase Alert: Your checking acct ending {last4} was debited ${amount} at {merchant} on {date_us}. Balance ${balance}",
             (), expense_type="transfer"),
    Template("citi_alt", "Citi Bank", "United States", "USD", "CITI-S", "debit",
             "Citi: Transaction of ${amount} on card ending {last4} at {merchant} is approved. Avl credit ${balance}",
             (), expense_type="shopping"),
    Template("hdfc_alt_debit", "HDFC Bank", "India", "INR", "HDFCBK-S", "debit",
             "HDFC Bank: Rs. {amount} debited from A/c XX{last4} on {date_mon} towards {merchant} via UPI {rrn}. Avl Bal INR {balance}",
             (), expense_type="transfer"),
    Template("icici_alt_upi", "ICICI Bank", "India", "INR", "ICICIB-S", "debit",
             "ICICI Bank A/c XX{last4} debited Rs. {amount} on {date_dmy} to {merchant} UPI:{rrn}. Avl Bal Rs.{balance}",
             (), expense_type="transfer"),
    Template("axis_alt_credit", "Axis Bank", "India", "INR", "AXISBK-S", "credit",
             "Axis Bank A/c XX{last4} credited INR {amount} on {date_dmy} from {merchant} (UPI {rrn}). Avl Bal INR {balance}",
             (), expense_type="income"),
    Template("bandhan_debit", "Bandhan Bank", "India", "INR", "BANDHN-S", "debit",
             "Bandhan Bank A/c XX{last4} debited Rs.{amount} on {date_dmy} towards {merchant}. Avl Bal Rs.{balance}",
             (), expense_type="transfer"),

)

_keys = [t.key for t in TEMPLATES]
if len(_keys) != len(set(_keys)):
    raise RuntimeError("duplicate template keys")
